# Generated by Django 3.0.5 on 2020-05-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_auto_20200506_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=0, verbose_name='Users can see it and answer it'),
            preserve_default=False,
        ),
    ]
